trigger:
  branches:
    include:
      - main  # or the branch you want to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: ExecuteSQLScripts
    jobs:
      - job: ExecuteOnDatabricks
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'  # Specify the Python version if needed

          - script: |
              pip install databricks-cli
              pip install requests
            displayName: 'Install Databricks CLI and Requests Library'

          - script: |
              python scripts/get_changed_sql_scripts.py
            displayName: 'Get Changed SQL Scripts using Azure DevOps API'

          - powershell: |
              $scripts = Get-Content changed_scripts.txt
              foreach ($script in $scripts) {
                Write-Host "Executing $script"
                databricks sql execute --catalog-name <your_catalog_name> --script-file $script
              }
            displayName: 'Execute Changed SQL Scripts on Databricks Catalog'
            env:
              DATABRICKS_HOST: $(databricksHost)
              DATABRICKS_TOKEN: $(databricksToken)

